# Configuration for KOMOE static site generator.

komoe_require = '0.5'

[project]
name = 'Komoe'

[plugin.sass]
package = "komoe_sass"
config.path = "style"
config.command = "sassc {input} > {output}"